import {Inter} from "next/font/google";
import "./globals.css";
import BasicsOfMotion from "@/components/BasicsOfMotion";
import Gestures from "@/components/Gestures";
import AnimationControls from "@/components/AnimationControls";
import ViewBasedAnimations from "@/components/ViewBasedAnimations";
import ScrollAnimations from "@/components/ScrollAnimations";
import Animations from "@/components/Animations";
import HorizontalScroll from "@/components/horizontalScroll";
import Motion3d from "@/components/motion3d";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {/* < BasicsOfMotion/> */}
        {/* <Gestures/> */}
        {/* <AnimationControls/> */}
        {/* <ViewBasedAnimations/> */}
        {/*<ScrollAnimations />*/}
        {/* {children} */}
        {/* <Animations/> */}
        {/* <HorizontalScroll /> */}
        <Motion3d />
        </body>
        </html>
    );
}
