import { Inter } from "next/font/google";
import "./globals.css";
import BasicsOfMotion from "@/components/BasicsOfMotion";
import Gestures from "@/components/Gestures";
import AnimationControls from "@/components/AnimationControls";
import ViewBasedAnimations from "@/components/ViewBasedAnimations";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* < BasicsOfMotion/> */}
        {/* <Gestures/> */}
        {/* <AnimationControls/> */}
        <ViewBasedAnimations />
        {children}
      </body>
    </html>
  );
}
